---
sidebar: sidebar 
permalink: task-discover-applications.html 
keywords: discover, admin role, service account, pre-canned policies 
summary: Découvrez les applications pour attribuer des stratégies et créer des sauvegardes. 
---
= Découvrir les applications
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez découvrir les bases de données sur l'hôte pour attribuer des stratégies et créer des sauvegardes.

*Ce dont vous aurez besoin*

* Vous devez avoir créé l'environnement de travail FSX pour ONTAP et le connecteur.
* Assurez-vous que le connecteur est connecté à l'environnement de travail FSX pour ONTAP et aux hôtes de base de données Oracle.
* Assurez-vous que l'utilisateur BlueXP a le rôle "Admin compte".
* Vous devez avoir déployé le plug-in SnapCenter pour Oracle. link:reference-prereq-protect-cloud-native-app-data.html#deploy-snapcenter-plug-in-for-oracle["En savoir plus >>"].


*Étapes*

. Dans l'interface utilisateur BlueXP, cliquez sur *protection* > *sauvegarde et récupération* > *applications*.
. Cliquez sur découvrir les applications.
. Sélectionnez *Cloud Native* et cliquez sur *Next*.
+
Un compte de service avec le rôle _SnapCenter System_ est créé pour exécuter des opérations de protection des données planifiées pour tous les utilisateurs de ce compte.

+
** Cliquez sur *compte* > *gérer compte* > *membres* pour afficher le compte de service.
+

NOTE: Le compte de service (_SnapCenter-account-<accountid>_) est utilisé pour l'exécution des opérations de sauvegarde planifiées. Vous ne devez jamais supprimer le compte de service.



. Dans la page Specify Host Details, entrez les détails de l'hôte de la base de données Oracle, cochez la case pour confirmer que le plug-in est installé sur l'hôte, puis cliquez sur *Discover*.
+
** Affiche toutes les bases de données sur l'hôte. Si l'authentification OS est désactivée pour la base de données, vous devez configurer l'authentification de la base de données en cliquant sur *configurer*. Pour plus d'informations, reportez-vous à la section <<Configurer les informations d'identification de la base de données Oracle>>.
** Cliquez sur *gérer l'application*, sélectionnez *Ajouter* pour ajouter un nouvel hôte, *Actualiser* pour découvrir de nouvelles bases de données ou *Supprimer* pour supprimer un hôte de base de données.
** Cliquez sur *Paramètres* et sélectionnez *stratégies* pour afficher les stratégies prédéfinies. Passez en revue les stratégies pré-prédéfinies et, si vous le souhaitez, vous pouvez les modifier pour répondre à vos exigences ou créer une nouvelle stratégie.






== Configurer les informations d'identification de la base de données Oracle

Vous devez configurer les informations d'identification utilisées pour effectuer des opérations de protection des données sur les bases de données Oracle.

*Étapes*

. Si l'authentification OS est désactivée pour la base de données, vous devez configurer l'authentification de la base de données en cliquant sur *configurer*.
. Spécifiez le nom d'utilisateur, le mot de passe et les détails du port dans la section Paramètres de la base de données ou Paramètres ASM.
+
L'utilisateur Oracle doit disposer des privilèges sysdba et l'utilisateur ASM doit disposer des privilèges sysasm.

. Cliquez sur *configurer*.




== Création de la règle

Vous pouvez créer des stratégies si vous ne souhaitez pas modifier les stratégies prédéfinies.

*Étapes*

. Dans la page applications, dans la liste déroulante Paramètres, sélectionnez *stratégies*.
. Cliquez sur *Créer une stratégie*.
. Spécifiez un nom de stratégie.
. (Facultatif) modifiez le format du nom de la sauvegarde.
. Spécifiez la planification et les informations de conservation.
. Cliquez sur *Créer*.

