---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: Vous pouvez restaurer la base de données SQL Server depuis le cloud vers le serveur SnapCenter sur site. 
---
= Restaurez la base de données SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez restaurer la base de données SQL Server sur le même hôte ou sur l'autre hôte. La restauration des sauvegardes de journaux et du réamorçage des groupes de disponibilité ne sont pas prises en charge.


NOTE: IMPORTANT : la restauration de sauvegardes secondaires via le stockage primaire est prise en charge.


IMPORTANT: La restauration de fichiers uniques (SFR) n'est pas prise en charge.

*Ce dont vous aurez besoin*

Si vous souhaitez restaurer une sauvegarde déplacée vers un magasin d'objets à partir d'un stockage secondaire, vous devez ajouter les informations relatives à l'environnement de travail principal et définir l'espace IP. Pour plus d'informations, voir link:task-manage-app-backups.html#set-ip-space-of-the-primary-working-environment["Définissez l'espace IP de l'environnement de travail principal"].

*Étapes*

. Dans l'interface utilisateur BlueXP, cliquez sur *protection* > *sauvegarde et récupération* > *applications*.
. Dans le champ *Filtrer par*, sélectionnez le filtre *Type* et sélectionnez *SQL* dans la liste déroulante.
. Cliquez sur *Afficher les détails* pour afficher toutes les sauvegardes disponibles.
. Sélectionnez la sauvegarde et cliquez sur *Restaurer*.
. Sélectionnez l'emplacement où vous souhaitez restaurer les fichiers de base de données.
+
|===
| Option | Description 


 a| 
Restaurez la base de données sur le même hôte où la sauvegarde a été créée
 a| 
Sélectionnez cette option si vous souhaitez restaurer la base de données sur le même serveur SQL où les sauvegardes sont effectuées.



 a| 
Restaurez la base de données sur un autre hôte
 a| 
Sélectionnez cette option si vous souhaitez que la base de données soit restaurée sur un autre serveur SQL dans le même hôte ou sur un hôte différent où des sauvegardes sont effectuées.

Sélectionnez un nom d'hôte, indiquez un nom de base de données (facultatif), sélectionnez une instance et spécifiez les chemins de restauration.


NOTE: L'extension de fichier fournie dans le chemin alternatif doit être identique à celle du fichier de base de données d'origine.

Si l'option *Restaurer la base de données sur un autre hôte* n'est pas affichée dans la page Restaurer l'étendue, effacez le cache du navigateur.

|===
. Si le snapshot est en stockage d'archivage, spécifiez la priorité de restauration des données à partir du stockage d'archivage.
. Sur la page *Options de pré-restauration*, sélectionnez l'une des options suivantes :
+
** Sélectionnez *Ecraser la base de données du même nom pendant la restauration* pour restaurer la base de données du même nom.
** Sélectionnez *conserver les paramètres de réplication de base de données SQL* pour restaurer la base de données et conserver les paramètres de réplication existants.


. Sur la page *Options de post-restauration*, pour spécifier l'état de la base de données pour restaurer des journaux transactionnels supplémentaires, sélectionnez l'une des options suivantes :
+
** Sélectionnez *opérationnel, mais indisponible* si vous restaurez maintenant toutes les sauvegardes nécessaires.
+
Il s'agit du comportement par défaut, qui laisse la base de données prête à l'emploi en revenant les transactions non validées. Vous ne pouvez pas restaurer d'autres journaux de transactions tant que vous n'avez pas créé de sauvegarde.

** Sélectionnez *non opérationnel, mais disponible* pour laisser la base de données non opérationnelle sans reprise des transactions non validées.
+
Des journaux de transactions supplémentaires peuvent être restaurés. Vous ne pouvez pas utiliser la base de données tant qu'elle n'a pas été restaurée.

** Sélectionnez *mode lecture seule et disponible* pour quitter la base de données en mode lecture seule.
+
Cette option annule les transactions non validées, mais enregistre les actions annulées dans un fichier de secours afin que les effets de récupération puissent être restaurés.

+
Si l'option Annuler le répertoire est activée, davantage de journaux de transactions sont restaurés. Si l'opération de restauration du journal de transactions échoue, les modifications peuvent être annulées. La documentation de SQL Server contient des informations supplémentaires.



. Vérifiez les détails et cliquez sur *Restaurer*.

